# Generated by Django 3.2.9 on 2021-12-21 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t4t', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
